name: zaza_app
description: "Zaza Asset Management System - FYP Project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  flutter_riverpod: ^2.6.1
  http: ^1.6.0
  intl: ^0.18.1
  fluttertoast: ^8.2.14
  fl_chart: ^0.69.0
  data_table_2: ^2.5.15
  csv: ^6.0.0
  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  syncfusion_flutter_datepicker: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
